// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: signer.proto

// Package conduit.signer.v1 defines the isolated signer service contract.
//
// Amount fields (value, max_fee_per_gas, max_priority_fee_per_gas) are uint256
// encoded as big-endian bytes of at most 32 bytes. Bytes are the canonical wire
// form for uint256 at this trust boundary: there is no decimal-string parsing to
// disagree on, no locale, and no precision loss — the signer and its callers
// interpret the exact same octets.

package signerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key_id selects which signing key to use inside the signer.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// chain_id is the EIP-155 chain identifier the transaction targets.
	ChainId uint64 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// nonce is the sender account nonce for this transaction.
	Nonce uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// to is the 20-byte destination address.
	To []byte `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// value is the transfer amount: uint256 big-endian, <=32 bytes.
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// gas_limit is the maximum gas units the transaction may consume.
	GasLimit uint64 `protobuf:"varint,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// max_fee_per_gas is the EIP-1559 fee cap: uint256 big-endian, <=32 bytes.
	MaxFeePerGas []byte `protobuf:"bytes,7,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	// max_priority_fee_per_gas is the EIP-1559 tip cap: uint256 big-endian, <=32 bytes.
	MaxPriorityFeePerGas []byte `protobuf:"bytes,8,opt,name=max_priority_fee_per_gas,json=maxPriorityFeePerGas,proto3" json:"max_priority_fee_per_gas,omitempty"`
	// data is the transaction calldata.
	Data          []byte `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	mi := &file_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{0}
}

func (x *SignTransactionRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignTransactionRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SignTransactionRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *SignTransactionRequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SignTransactionRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SignTransactionRequest) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *SignTransactionRequest) GetMaxFeePerGas() []byte {
	if x != nil {
		return x.MaxFeePerGas
	}
	return nil
}

func (x *SignTransactionRequest) GetMaxPriorityFeePerGas() []byte {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return nil
}

func (x *SignTransactionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// raw_transaction is the RLP-encoded signed transaction ready to broadcast.
	RawTransaction []byte `protobuf:"bytes,1,opt,name=raw_transaction,json=rawTransaction,proto3" json:"raw_transaction,omitempty"`
	// tx_hash is the keccak256 hash of the signed transaction.
	TxHash []byte `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// from is the 0x-prefixed EIP-55 checksummed sender address.
	From          string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	mi := &file_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{1}
}

func (x *SignTransactionResponse) GetRawTransaction() []byte {
	if x != nil {
		return x.RawTransaction
	}
	return nil
}

func (x *SignTransactionResponse) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *SignTransactionResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

var File_signer_proto protoreflect.FileDescriptor

const file_signer_proto_rawDesc = "" +
	"\n" +
	"\fsigner.proto\x12\x11conduit.signer.v1\"\x96\x02\n" +
	"\x16SignTransactionRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x1b\n" +
	"\tgas_limit\x18\x06 \x01(\x04R\bgasLimit\x12%\n" +
	"\x0fmax_fee_per_gas\x18\a \x01(\fR\fmaxFeePerGas\x126\n" +
	"\x18max_priority_fee_per_gas\x18\b \x01(\fR\x14maxPriorityFeePerGas\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\"o\n" +
	"\x17SignTransactionResponse\x12'\n" +
	"\x0fraw_transaction\x18\x01 \x01(\fR\x0erawTransaction\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from2y\n" +
	"\rSignerService\x12h\n" +
	"\x0fSignTransaction\x12).conduit.signer.v1.SignTransactionRequest\x1a*.conduit.signer.v1.SignTransactionResponseB:Z8github.com/dz3ka/payment-rail/internal/signerpb;signerpbb\x06proto3"

var (
	file_signer_proto_rawDescOnce sync.Once
	file_signer_proto_rawDescData []byte
)

func file_signer_proto_rawDescGZIP() []byte {
	file_signer_proto_rawDescOnce.Do(func() {
		file_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signer_proto_rawDesc), len(file_signer_proto_rawDesc)))
	})
	return file_signer_proto_rawDescData
}

var file_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signer_proto_goTypes = []any{
	(*SignTransactionRequest)(nil),  // 0: conduit.signer.v1.SignTransactionRequest
	(*SignTransactionResponse)(nil), // 1: conduit.signer.v1.SignTransactionResponse
}
var file_signer_proto_depIdxs = []int32{
	0, // 0: conduit.signer.v1.SignerService.SignTransaction:input_type -> conduit.signer.v1.SignTransactionRequest
	1, // 1: conduit.signer.v1.SignerService.SignTransaction:output_type -> conduit.signer.v1.SignTransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_signer_proto_init() }
func file_signer_proto_init() {
	if File_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signer_proto_rawDesc), len(file_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signer_proto_goTypes,
		DependencyIndexes: file_signer_proto_depIdxs,
		MessageInfos:      file_signer_proto_msgTypes,
	}.Build()
	File_signer_proto = out.File
	file_signer_proto_goTypes = nil
	file_signer_proto_depIdxs = nil
}
