// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getApprovalForUpdate = `-- name: GetApprovalForUpdate :one
SELECT id, to_address, amount, asset, key_id, payment_id, proposer, approver, status, tx_hash, created_at FROM payment_approvals
WHERE id = $1
FOR UPDATE
`

// Locks the row for the duration of the claim transaction so a concurrent
// approver blocks rather than racing past the status guard.
func (q *Queries) GetApprovalForUpdate(ctx context.Context, id uuid.UUID) (PaymentApproval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalForUpdate, id)
	var i PaymentApproval
	err := row.Scan(
		&i.ID,
		&i.ToAddress,
		&i.Amount,
		&i.Asset,
		&i.KeyID,
		&i.PaymentID,
		&i.Proposer,
		&i.Approver,
		&i.Status,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertPaymentApproval = `-- name: InsertPaymentApproval :one
INSERT INTO payment_approvals (to_address, amount, asset, key_id, payment_id, proposer)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertPaymentApprovalParams struct {
	ToAddress string
	Amount    int64
	Asset     string
	KeyID     string
	PaymentID uuid.NullUUID
	Proposer  string
}

// Parks a payment's full intent as a pending approval attributed to its proposer.
// Returns the generated id so the submit path can reference the queued row.
func (q *Queries) InsertPaymentApproval(ctx context.Context, arg InsertPaymentApprovalParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertPaymentApproval,
		arg.ToAddress,
		arg.Amount,
		arg.Asset,
		arg.KeyID,
		arg.PaymentID,
		arg.Proposer,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markApprovalApproved = `-- name: MarkApprovalApproved :execrows
UPDATE payment_approvals
SET status = 'approved', approver = $2
WHERE id = $1 AND status = 'pending'
`

type MarkApprovalApprovedParams struct {
	ID       uuid.UUID
	Approver sql.NullString
}

// Guarded on status = 'pending' so a concurrent or repeated claim matches no row;
// the rows-affected count lets the caller detect an already-claimed approval.
func (q *Queries) MarkApprovalApproved(ctx context.Context, arg MarkApprovalApprovedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markApprovalApproved, arg.ID, arg.Approver)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markApprovalBroadcast = `-- name: MarkApprovalBroadcast :execrows
UPDATE payment_approvals
SET tx_hash = $2
WHERE id = $1 AND status = 'approved' AND tx_hash IS NULL
`

type MarkApprovalBroadcastParams struct {
	ID     uuid.UUID
	TxHash sql.NullString
}

// Guarded on status = 'approved' AND tx_hash IS NULL so a double-broadcast matches
// no row; the rows-affected count lets the caller detect an already-broadcast row.
func (q *Queries) MarkApprovalBroadcast(ctx context.Context, arg MarkApprovalBroadcastParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markApprovalBroadcast, arg.ID, arg.TxHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reopenApproval = `-- name: ReopenApproval :execrows
UPDATE payment_approvals
SET status = 'pending', approver = NULL
WHERE id = $1 AND status = 'approved' AND tx_hash IS NULL
`

// Reverts a claimed-but-never-broadcast approval back to pending so a retry can
// re-claim it after a pre-send broadcast failure. Guarded on status = 'approved'
// AND tx_hash IS NULL: once a broadcast has landed (tx_hash set) reopen matches no
// row, so a sent payment can never be resurrected. The rows-affected count lets the
// caller detect a row that was not in the reopenable state.
func (q *Queries) ReopenApproval(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, reopenApproval, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
