// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"
)

const acquireAuditChainLock = `-- name: AcquireAuditChainLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Serialize the whole chain: the xact-scoped advisory lock releases at
// commit/rollback, so concurrent appenders can't both read the same head and
// assign the same seq / prev_hash, which would fork the chain.
func (q *Queries) AcquireAuditChainLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.ExecContext(ctx, acquireAuditChainLock, lockKey)
	return err
}

const getAuditHead = `-- name: GetAuditHead :one
SELECT seq, entry_hash FROM audit_log ORDER BY seq DESC LIMIT 1
`

type GetAuditHeadRow struct {
	Seq       int64
	EntryHash []byte
}

// The current tail of the chain, whose entry_hash becomes the next row's
// prev_hash and whose seq + 1 becomes the next seq. Callers treat sql.ErrNoRows
// as the empty chain: the first row is seq 1 with prev = 32 zero bytes (genesis).
func (q *Queries) GetAuditHead(ctx context.Context) (GetAuditHeadRow, error) {
	row := q.db.QueryRowContext(ctx, getAuditHead)
	var i GetAuditHeadRow
	err := row.Scan(&i.Seq, &i.EntryHash)
	return i, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (seq, prev_hash, entry_hash, actor, action, aggregate_type, aggregate_id, occurred_at, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditEntryParams struct {
	Seq           int64
	PrevHash      []byte
	EntryHash     []byte
	Actor         string
	Action        string
	AggregateType string
	AggregateID   string
	OccurredAt    time.Time
	Payload       []byte
}

// Appends one already-hashed row. seq, prev_hash and entry_hash are computed by
// the app from the head read under the chain lock in the same transaction.
func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEntry,
		arg.Seq,
		arg.PrevHash,
		arg.EntryHash,
		arg.Actor,
		arg.Action,
		arg.AggregateType,
		arg.AggregateID,
		arg.OccurredAt,
		arg.Payload,
	)
	return err
}

const scanAuditChain = `-- name: ScanAuditChain :many
SELECT seq, prev_hash, entry_hash, actor, action, aggregate_type, aggregate_id, occurred_at, payload
FROM audit_log ORDER BY seq ASC
`

// The full chain oldest-first, so a verifier can rehash each row against its
// predecessor and confirm no historical row was altered or removed.
func (q *Queries) ScanAuditChain(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, scanAuditChain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.Seq,
			&i.PrevHash,
			&i.EntryHash,
			&i.Actor,
			&i.Action,
			&i.AggregateType,
			&i.AggregateID,
			&i.OccurredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
