// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status = 'completed', response_status = $2, response_body = $3, payment_id = $4, completed_at = now()
WHERE key = $1
`

type CompleteIdempotencyKeyParams struct {
	Key            string
	ResponseStatus sql.NullInt32
	ResponseBody   []byte
	PaymentID      uuid.NullUUID
}

// Caches the response so subsequent retries of the same key replay it verbatim.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, completeIdempotencyKey,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.PaymentID,
	)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE created_at < $1
`

// TTL sweeper: drop keys created before the caller-supplied cutoff.
func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredIdempotencyKeys, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE key = $1
`

// Releases a claim whose handler failed, so the key isn't stuck in_flight.
func (q *Queries) DeleteIdempotencyKey(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteIdempotencyKey, key)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_hash, status, response_status, response_body, payment_id, created_at, completed_at FROM idempotency_keys
WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.PaymentID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (key, request_hash, status)
VALUES ($1, $2, 'in_flight')
ON CONFLICT DO NOTHING
RETURNING key, request_hash, status, response_status, response_body, payment_id, created_at, completed_at
`

type InsertIdempotencyKeyParams struct {
	Key         string
	RequestHash []byte
}

// Claims a key for an in-flight request. ON CONFLICT DO NOTHING means a key that
// already exists returns zero rows, so the caller gets sql.ErrNoRows — that is
// the "key already taken" signal, which the handler resolves against the stored
// request_hash/response rather than re-running the operation.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, insertIdempotencyKey, arg.Key, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.PaymentID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
