// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, kind, asset)
VALUES ($1, $2, $3)
RETURNING id, name, kind, asset, status, created_at
`

type CreateAccountParams struct {
	Name  string
	Kind  string
	Asset string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Kind, arg.Asset)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Asset,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, kind, asset, status, created_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Asset,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT COALESCE(
    SUM(CASE WHEN direction = 'credit' THEN amount ELSE -amount END),
    0
)::bigint AS balance
FROM entry_lines
WHERE account_id = $1
`

// Derived balance: credits add, debits subtract; never stored.
func (q *Queries) GetAccountBalance(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getAccountByNameAndAsset = `-- name: GetAccountByNameAndAsset :one
SELECT id, name, kind, asset, status, created_at FROM accounts
WHERE name = $1 AND asset = $2
`

type GetAccountByNameAndAssetParams struct {
	Name  string
	Asset string
}

// Resolves a seeded/house account (e.g. the onchain_settlement clearing
// account) by its UNIQUE (name, asset) key.
func (q *Queries) GetAccountByNameAndAsset(ctx context.Context, arg GetAccountByNameAndAssetParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByNameAndAsset, arg.Name, arg.Asset)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Asset,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountsForUpdate = `-- name: GetAccountsForUpdate :many
SELECT id, name, kind, asset, status, created_at FROM accounts
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

// Production locking path: lock the named account rows for the duration of the
// surrounding transaction, ordered by id to impose a deterministic lock order
// and avoid deadlocks between concurrent transfers. WP2 calls this on Querier.
func (q *Queries) GetAccountsForUpdate(ctx context.Context, ids []uuid.UUID) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountsForUpdate, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Asset,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEntryLine = `-- name: InsertEntryLine :one
INSERT INTO entry_lines (entry_id, account_id, direction, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, entry_id, account_id, direction, amount
`

type InsertEntryLineParams struct {
	EntryID   uuid.UUID
	AccountID uuid.UUID
	Direction string
	Amount    int64
}

func (q *Queries) InsertEntryLine(ctx context.Context, arg InsertEntryLineParams) (EntryLine, error) {
	row := q.db.QueryRowContext(ctx, insertEntryLine,
		arg.EntryID,
		arg.AccountID,
		arg.Direction,
		arg.Amount,
	)
	var i EntryLine
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.AccountID,
		&i.Direction,
		&i.Amount,
	)
	return i, err
}

const insertJournalEntry = `-- name: InsertJournalEntry :one
INSERT INTO journal_entries (kind, external_ref, asset)
VALUES ($1, $2, $3)
RETURNING id, kind, external_ref, asset, created_at
`

type InsertJournalEntryParams struct {
	Kind        string
	ExternalRef string
	Asset       string
}

func (q *Queries) InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, insertJournalEntry, arg.Kind, arg.ExternalRef, arg.Asset)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalRef,
		&i.Asset,
		&i.CreatedAt,
	)
	return i, err
}
