// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	Asset     string
	Status    string
	CreatedAt time.Time
}

type EntryLine struct {
	ID        int64
	EntryID   uuid.UUID
	AccountID uuid.UUID
	Direction string
	Amount    int64
}

type IdempotencyKey struct {
	Key            string
	RequestHash    []byte
	Status         string
	ResponseStatus sql.NullInt32
	ResponseBody   []byte
	PaymentID      uuid.NullUUID
	CreatedAt      time.Time
	CompletedAt    sql.NullTime
}

type JournalEntry struct {
	ID          uuid.UUID
	Kind        string
	ExternalRef string
	Asset       string
	CreatedAt   time.Time
}

type Outbox struct {
	ID          uuid.UUID
	EventType   string
	AggregateID string
	Payload     json.RawMessage
	CreatedAt   time.Time
	SentAt      sql.NullTime
}

type Payment struct {
	ID              uuid.UUID
	Status          string
	Asset           string
	Amount          int64
	SourceAccountID uuid.UUID
	DestAccountID   uuid.UUID
	JournalEntryID  uuid.UUID
	ReversalEntryID uuid.NullUUID
	CreatedAt       time.Time
	CanceledAt      sql.NullTime
}

type Settlement struct {
	ID                 uuid.UUID
	PaymentID          uuid.UUID
	TxHash             string
	Status             string
	SettleEntryID      uuid.NullUUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SettledBlockHash   sql.NullString
	SettledBlockNumber sql.NullInt64
}

type VelocityEvent struct {
	ID         uuid.UUID
	KeyID      string
	Amount     int64
	OccurredAt time.Time
}

type WebhookDelivery struct {
	ID             uuid.UUID
	EventID        uuid.UUID
	SubscriptionID uuid.UUID
	EventType      string
	Payload        json.RawMessage
	Status         string
	Attempts       int32
	NextAttemptAt  time.Time
	LastStatusCode sql.NullInt32
	LastError      sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WebhookSubscription struct {
	ID            uuid.UUID
	Url           string
	EventTypes    []string
	SigningSecret string
	Active        bool
	CreatedAt     time.Time
}
