// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	Asset     string
	Status    string
	CreatedAt time.Time
}

type EntryLine struct {
	ID        int64
	EntryID   uuid.UUID
	AccountID uuid.UUID
	Direction string
	Amount    int64
}

type IdempotencyKey struct {
	Key            string
	RequestHash    []byte
	Status         string
	ResponseStatus sql.NullInt32
	ResponseBody   []byte
	PaymentID      uuid.NullUUID
	CreatedAt      time.Time
	CompletedAt    sql.NullTime
}

type JournalEntry struct {
	ID          uuid.UUID
	Kind        string
	ExternalRef string
	Asset       string
	CreatedAt   time.Time
}

type Payment struct {
	ID              uuid.UUID
	Status          string
	Asset           string
	Amount          int64
	SourceAccountID uuid.UUID
	DestAccountID   uuid.UUID
	JournalEntryID  uuid.UUID
	ReversalEntryID uuid.NullUUID
	CreatedAt       time.Time
	CanceledAt      sql.NullTime
}
