// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const claimUnsentOutbox = `-- name: ClaimUnsentOutbox :many
SELECT id, event_type, aggregate_id, payload, created_at, sent_at FROM outbox
WHERE sent_at IS NULL
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// The relay's claim scan: oldest unsent rows first, FOR UPDATE SKIP LOCKED so
// concurrent relay workers each grab a disjoint batch without blocking.
func (q *Queries) ClaimUnsentOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, claimUnsentOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (id, event_type, aggregate_id, payload)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxEventParams struct {
	ID          uuid.UUID
	EventType   string
	AggregateID string
	Payload     json.RawMessage
}

// Appended in the same transaction as the aggregate write it describes, so the
// domain change and its intent-to-publish commit atomically.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.Payload,
	)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :execrows
UPDATE outbox SET sent_at = now()
WHERE id = ANY($1::uuid[])
`

// Stamps a claimed batch as published; ANY($1) marks the whole batch in one
// round-trip after Kafka acks.
func (q *Queries) MarkOutboxSent(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxSent, pq.Array(dollar_1))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
