// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelPayment = `-- name: CancelPayment :one
UPDATE payments
SET status = 'canceled', reversal_entry_id = $2, canceled_at = now()
WHERE id = $1 AND status = 'completed'
RETURNING id, status, asset, amount, source_account_id, dest_account_id, journal_entry_id, reversal_entry_id, created_at, canceled_at
`

type CancelPaymentParams struct {
	ID              uuid.UUID
	ReversalEntryID uuid.NullUUID
}

// Guarded on status = 'completed' so a concurrent or repeated cancel matches no
// row and the caller sees sql.ErrNoRows instead of double-reversing.
func (q *Queries) CancelPayment(ctx context.Context, arg CancelPaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, cancelPayment, arg.ID, arg.ReversalEntryID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Asset,
		&i.Amount,
		&i.SourceAccountID,
		&i.DestAccountID,
		&i.JournalEntryID,
		&i.ReversalEntryID,
		&i.CreatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, status, asset, amount, source_account_id, dest_account_id, journal_entry_id, reversal_entry_id, created_at, canceled_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Asset,
		&i.Amount,
		&i.SourceAccountID,
		&i.DestAccountID,
		&i.JournalEntryID,
		&i.ReversalEntryID,
		&i.CreatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (id, status, asset, amount, source_account_id, dest_account_id, journal_entry_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, status, asset, amount, source_account_id, dest_account_id, journal_entry_id, reversal_entry_id, created_at, canceled_at
`

type InsertPaymentParams struct {
	ID              uuid.UUID
	Status          string
	Asset           string
	Amount          int64
	SourceAccountID uuid.UUID
	DestAccountID   uuid.UUID
	JournalEntryID  uuid.UUID
}

// Records a completed payment. status/created_at default appropriately; a
// canceled payment is only ever reached via CancelPayment, never inserted.
func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, insertPayment,
		arg.ID,
		arg.Status,
		arg.Asset,
		arg.Amount,
		arg.SourceAccountID,
		arg.DestAccountID,
		arg.JournalEntryID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Asset,
		&i.Amount,
		&i.SourceAccountID,
		&i.DestAccountID,
		&i.JournalEntryID,
		&i.ReversalEntryID,
		&i.CreatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const listPaymentsAfter = `-- name: ListPaymentsAfter :many
SELECT id, status, asset, amount, source_account_id, dest_account_id, journal_entry_id, reversal_entry_id, created_at, canceled_at FROM payments
WHERE (created_at, id) < ($1::timestamptz, $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListPaymentsAfterParams struct {
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageLimit      int32
}

// Keyset continuation: everything strictly older than the cursor. The row-value
// comparison (created_at, id) < ($1, $2) is a single index range scan over
// idx_payments_keyset — stable under inserts and free of OFFSET's skew.
func (q *Queries) ListPaymentsAfter(ctx context.Context, arg ListPaymentsAfterParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsAfter, arg.AfterCreatedAt, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Asset,
			&i.Amount,
			&i.SourceAccountID,
			&i.DestAccountID,
			&i.JournalEntryID,
			&i.ReversalEntryID,
			&i.CreatedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsFirstPage = `-- name: ListPaymentsFirstPage :many
SELECT id, status, asset, amount, source_account_id, dest_account_id, journal_entry_id, reversal_entry_id, created_at, canceled_at FROM payments
ORDER BY created_at DESC, id DESC
LIMIT $1
`

// Newest-first page; the keyset cursor for the next page is the last row's
// (created_at, id). Matches idx_payments_keyset.
func (q *Queries) ListPaymentsFirstPage(ctx context.Context, limit int32) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Asset,
			&i.Amount,
			&i.SourceAccountID,
			&i.DestAccountID,
			&i.JournalEntryID,
			&i.ReversalEntryID,
			&i.CreatedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
