// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listSettlementsForReconcileAfter = `-- name: ListSettlementsForReconcileAfter :many
SELECT s.id, s.created_at, s.status, p.asset, p.amount
FROM settlements s
JOIN payments p ON p.id = s.payment_id
WHERE s.status IN ('settled', 'finalized')
  AND (s.created_at, s.id) > ($1::timestamptz, $2::uuid)
ORDER BY s.created_at, s.id
LIMIT $3
`

type ListSettlementsForReconcileAfterParams struct {
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageLimit      int32
}

type ListSettlementsForReconcileAfterRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Status    string
	Asset     string
	Amount    int64
}

// Keyset continuation: everything strictly after the cursor. The row-value
// comparison (created_at, id) > (@after_created_at, @after_id) is a single
// index range scan, stable under concurrent inserts and free of OFFSET's skew.
func (q *Queries) ListSettlementsForReconcileAfter(ctx context.Context, arg ListSettlementsForReconcileAfterParams) ([]ListSettlementsForReconcileAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettlementsForReconcileAfter, arg.AfterCreatedAt, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementsForReconcileAfterRow{}
	for rows.Next() {
		var i ListSettlementsForReconcileAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Status,
			&i.Asset,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementsForReconcileFirstPage = `-- name: ListSettlementsForReconcileFirstPage :many
SELECT s.id, s.created_at, s.status, p.asset, p.amount
FROM settlements s
JOIN payments p ON p.id = s.payment_id
WHERE s.status IN ('settled', 'finalized')
ORDER BY s.created_at, s.id
LIMIT $1
`

type ListSettlementsForReconcileFirstPageRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Status    string
	Asset     string
	Amount    int64
}

// First keyset page of settlements that count toward the ledger's on-chain
// expectation: only 'settled' (confirmed, not yet final) and 'finalized' rows.
// Amount/asset live on the payment, so we join. Ordered ASC by (created_at, id)
// — the reconcile job pages forward, oldest-first, so a mid-scan insert lands
// past the cursor and is simply picked up on a later run. The cursor for the
// next page is the last row's (created_at, id).
func (q *Queries) ListSettlementsForReconcileFirstPage(ctx context.Context, limit int32) ([]ListSettlementsForReconcileFirstPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettlementsForReconcileFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementsForReconcileFirstPageRow{}
	for rows.Next() {
		var i ListSettlementsForReconcileFirstPageRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Status,
			&i.Asset,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumNonHouseLiabilities = `-- name: SumNonHouseLiabilities :one
SELECT COALESCE(
    SUM(CASE WHEN el.direction = 'credit' THEN el.amount ELSE -el.amount END),
    0
)::bigint
FROM entry_lines el
JOIN accounts a ON a.id = el.account_id
WHERE a.kind <> 'onchain_settlement' AND a.asset = $1
`

// Per-asset Σ(credit − debit) over every account EXCEPT the onchain_settlement
// house account. This is the (signed) sum of user-facing balances; the Go caller
// negates it to get liabilities = −Σ(non-house balances) for proof-of-reserves.
func (q *Queries) SumNonHouseLiabilities(ctx context.Context, asset string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumNonHouseLiabilities, asset)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
