// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: velocity.sql

package db

import (
	"context"
	"time"
)

const acquireVelocityLock = `-- name: AcquireVelocityLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Serialize check-then-insert for one signing key: the xact-scoped advisory lock
// releases at commit/rollback, so concurrent submissions on the same key can't
// both read a stale window sum and race past the ceiling.
func (q *Queries) AcquireVelocityLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.ExecContext(ctx, acquireVelocityLock, lockKey)
	return err
}

const insertVelocityEvent = `-- name: InsertVelocityEvent :exec
INSERT INTO velocity_events (key_id, amount, occurred_at)
VALUES ($1, $2, $3)
`

type InsertVelocityEventParams struct {
	KeyID      string
	Amount     int64
	OccurredAt time.Time
}

func (q *Queries) InsertVelocityEvent(ctx context.Context, arg InsertVelocityEventParams) error {
	_, err := q.db.ExecContext(ctx, insertVelocityEvent, arg.KeyID, arg.Amount, arg.OccurredAt)
	return err
}

const sumVelocityWindow = `-- name: SumVelocityWindow :one
SELECT COUNT(*)::bigint AS count, COALESCE(SUM(amount), 0)::bigint AS sum
FROM velocity_events
WHERE key_id = $1 AND occurred_at >= $2
`

type SumVelocityWindowParams struct {
	KeyID string
	Since time.Time
}

type SumVelocityWindowRow struct {
	Count int64
	Sum   int64
}

// Count and total amount of a key's events since the window start.
func (q *Queries) SumVelocityWindow(ctx context.Context, arg SumVelocityWindowParams) (SumVelocityWindowRow, error) {
	row := q.db.QueryRowContext(ctx, sumVelocityWindow, arg.KeyID, arg.Since)
	var i SumVelocityWindowRow
	err := row.Scan(&i.Count, &i.Sum)
	return i, err
}
