// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many
UPDATE webhook_deliveries d
SET next_attempt_at = now() + make_interval(secs => $1::int),
    updated_at = now()
FROM webhook_subscriptions s
WHERE d.subscription_id = s.id
  AND d.id IN (
      SELECT id FROM webhook_deliveries
      WHERE status = 'pending' AND next_attempt_at <= now()
      ORDER BY next_attempt_at
      LIMIT $2::int
      FOR UPDATE SKIP LOCKED
  )
RETURNING d.id, d.event_id, d.attempts, d.payload, s.url, s.signing_secret
`

type ClaimDueDeliveriesParams struct {
	LeaseSeconds int32
	ClaimLimit   int32
}

type ClaimDueDeliveriesRow struct {
	ID            uuid.UUID
	EventID       uuid.UUID
	Attempts      int32
	Payload       json.RawMessage
	Url           string
	SigningSecret string
}

// Atomically claim due pending deliveries and push their next_attempt_at forward
// by a lease so a crashed/slow worker's rows are not re-claimed until the lease expires.
func (q *Queries) ClaimDueDeliveries(ctx context.Context, arg ClaimDueDeliveriesParams) ([]ClaimDueDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, claimDueDeliveries, arg.LeaseSeconds, arg.ClaimLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueDeliveriesRow{}
	for rows.Next() {
		var i ClaimDueDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Attempts,
			&i.Payload,
			&i.Url,
			&i.SigningSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fanOutDelivery = `-- name: FanOutDelivery :execrows
INSERT INTO webhook_deliveries (event_id, subscription_id, event_type, payload)
SELECT $1, s.id, $2, $3
FROM webhook_subscriptions s
WHERE s.active AND $2 = ANY(s.event_types)
ON CONFLICT (event_id, subscription_id) DO NOTHING
`

type FanOutDeliveryParams struct {
	EventID   uuid.UUID
	EventType string
	Payload   json.RawMessage
}

// Insert one pending delivery per active subscription matching the event type.
// Idempotent on redelivery via the (event_id, subscription_id) unique constraint.
func (q *Queries) FanOutDelivery(ctx context.Context, arg FanOutDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, fanOutDelivery, arg.EventID, arg.EventType, arg.Payload)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markDeliveryDeadLettered = `-- name: MarkDeliveryDeadLettered :exec
UPDATE webhook_deliveries
SET status = 'dead_letter', attempts = $2, last_status_code = $3,
    last_error = $4, updated_at = now()
WHERE id = $1
`

type MarkDeliveryDeadLetteredParams struct {
	ID             uuid.UUID
	Attempts       int32
	LastStatusCode sql.NullInt32
	LastError      sql.NullString
}

func (q *Queries) MarkDeliveryDeadLettered(ctx context.Context, arg MarkDeliveryDeadLetteredParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryDeadLettered,
		arg.ID,
		arg.Attempts,
		arg.LastStatusCode,
		arg.LastError,
	)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE webhook_deliveries
SET attempts = $2, next_attempt_at = $3, last_status_code = $4,
    last_error = $5, updated_at = now()
WHERE id = $1
`

type MarkDeliveryRetryParams struct {
	ID             uuid.UUID
	Attempts       int32
	NextAttemptAt  time.Time
	LastStatusCode sql.NullInt32
	LastError      sql.NullString
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryRetry,
		arg.ID,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastStatusCode,
		arg.LastError,
	)
	return err
}

const markDeliverySucceeded = `-- name: MarkDeliverySucceeded :exec
UPDATE webhook_deliveries
SET status = 'delivered', attempts = $2, last_status_code = $3,
    last_error = NULL, updated_at = now()
WHERE id = $1
`

type MarkDeliverySucceededParams struct {
	ID             uuid.UUID
	Attempts       int32
	LastStatusCode sql.NullInt32
}

func (q *Queries) MarkDeliverySucceeded(ctx context.Context, arg MarkDeliverySucceededParams) error {
	_, err := q.db.ExecContext(ctx, markDeliverySucceeded, arg.ID, arg.Attempts, arg.LastStatusCode)
	return err
}

const replayDeadLettered = `-- name: ReplayDeadLettered :execrows
UPDATE webhook_deliveries
SET status = 'pending', attempts = 0, next_attempt_at = now(),
    last_error = NULL, updated_at = now()
WHERE status = 'dead_letter' AND subscription_id = $1
`

// Re-drive every dead-lettered delivery for one subscription (operator action
// after fixing a broken endpoint): reset to pending, clear error, deliver now.
func (q *Queries) ReplayDeadLettered(ctx context.Context, subscriptionID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, replayDeadLettered, subscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
